Confirm your account

An account named {{ $username }} was registered with this address.
Enter this code to activate it:

    {{ $code }}

Or open the link below instead.

{{--
    The URL is printed unescaped on purpose.

    This is the plain-text part of the message, so there is no HTML context to
    escape for -- and Blade's {{ }} would turn the `&` between query parameters
    into `&amp;`, which in plain text is five literal characters. Somebody
    copying the link out of a text-only mail client would paste a broken URL.

    Nothing user-supplied is interpolated: the address comes from APP_URL, the
    token is hex generated by SecureToken, and the server key is a key from
    config/rathena.php.
--}}
{!! $actionUrl !!}

The code and the link are valid for {{ $expiresInHours }} {{ \Illuminate\Support\Str::plural('hour', $expiresInHours) }} and can be used once.
Until one of them is used, the account cannot sign in.

If you did not register this account, you can ignore this message. It will not
be activated, and the name will be released for someone else to use.
@if ($gameName !== '')

-- {{ $gameName }}
@endif
