Confirm your new e-mail address

The account {{ $username }} asked to use {{ $newEmail }} as its e-mail address.
Open the link below to confirm it.

{{--
    The URL is printed unescaped on purpose.

    This is the plain-text part of the message, so there is no HTML context to
    escape for -- and Blade's {{ }} would turn the `&` between query parameters
    into `&amp;`, which in plain text is five literal characters. Somebody
    copying the link out of a text-only mail client would paste a broken URL.

    Nothing user-supplied is interpolated: the address comes from APP_URL, the
    token is hex generated by SecureToken, and the server key is a key from
    config/rathena.php.
--}}
{!! $actionUrl !!}

The link is valid for {{ $expiresInHours }} {{ \Illuminate\Support\Str::plural('hour', $expiresInHours) }} and can be used once.
The account keeps its current address until you open it.

If you did not ask for this, you can ignore this message. The address on the
account will not be changed.
@if ($gameName !== '')

-- {{ $gameName }}
@endif
