Choose a new password

Somebody asked to reset the password for {{ $username }}.
Open the link below to choose a new one.

{{--
    The URL is printed unescaped on purpose.

    This is the plain-text part of the message, so there is no HTML context to
    escape for -- and Blade's {{ }} would turn the `&` between query parameters
    into `&amp;`, which in plain text is five literal characters. Somebody
    copying the link out of a text-only mail client would paste a broken URL.

    Nothing user-supplied is interpolated: the address comes from APP_URL, the
    token is hex generated by SecureToken, and the server key is a key from
    config/rathena.php.
--}}
{!! $actionUrl !!}

The link is valid for {{ $expiresInHours }} {{ \Illuminate\Support\Str::plural('hour', $expiresInHours) }} and can be used once.
Your current password keeps working until you set a new one.

If you did not ask for this, you can ignore this message. Your password has not
been changed, and nobody can change it without this link.
@if ($gameName !== '')

-- {{ $gameName }}
@endif
