<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| rAthena reference data
|--------------------------------------------------------------------------
|
| Job and homunculus class names, ported from FluxCP's config/jobs.php and
| config/homunculus.php.
|
| These are names for ids the emulator stores as bare integers, and rAthena
| does not expose them to the panel, so they have to live somewhere. They are
| configuration rather than code because a server with custom jobs needs to
| extend them, which is exactly why FluxCP kept them in config too.
|
| Deliberately not duplicated in the frontend: the API returns the resolved
| name alongside the id, so this mapping exists once.
|
*/

return [

    /*
     * Values of char.class.
     */
    'jobs' => [
        0 => 'Novice',
        1 => 'Swordsman',
        2 => 'Mage',
        3 => 'Archer',
        4 => 'Acolyte',
        5 => 'Merchant',
        6 => 'Thief',
        7 => 'Knight',
        8 => 'Priest',
        9 => 'Wizard',
        10 => 'Blacksmith',
        11 => 'Hunter',
        12 => 'Assassin',
        14 => 'Crusader',
        15 => 'Monk',
        16 => 'Sage',
        17 => 'Rogue',
        18 => 'Alchemist',
        19 => 'Bard',
        20 => 'Dancer',
        22 => 'Wedding',
        23 => 'Super Novice',
        24 => 'Gunslinger',
        25 => 'Ninja',
        26 => 'Xmas',
        27 => 'Summer',
        28 => 'Hanbok',
        29 => 'Oktoberfest',
        4001 => 'High Novice',
        4002 => 'High Swordsman',
        4003 => 'High Mage',
        4004 => 'High Archer',
        4005 => 'High Acolyte',
        4006 => 'High Merchant',
        4007 => 'High Thief',
        4008 => 'Lord Knight',
        4009 => 'High Priest',
        4010 => 'High Wizard',
        4011 => 'Whitesmith',
        4012 => 'Sniper',
        4013 => 'Assassin Cross',
        4015 => 'Paladin',
        4016 => 'Champion',
        4017 => 'Professor',
        4018 => 'Stalker',
        4019 => 'Creator',
        4020 => 'Clown',
        4021 => 'Gypsy',
        4023 => 'Baby',
        4024 => 'Baby Swordsman',
        4025 => 'Baby Mage',
        4026 => 'Baby Archer',
        4027 => 'Baby Acolyte',
        4028 => 'Baby Merchant',
        4029 => 'Baby Thief',
        4030 => 'Baby Knight',
        4031 => 'Baby Priest',
        4032 => 'Baby Wizard',
        4033 => 'Baby Blacksmith',
        4034 => 'Baby Hunter',
        4035 => 'Baby Assassin',
        4037 => 'Baby Crusader',
        4038 => 'Baby Monk',
        4039 => 'Baby Sage',
        4040 => 'Baby Rogue',
        4041 => 'Baby Alchemist',
        4042 => 'Baby Bard',
        4043 => 'Baby Dancer',
        4045 => 'Super Baby',
        4046 => 'Taekwon',
        4047 => 'Star Gladiator',
        4049 => 'Soul Linker',
        4050 => 'Jiang Shi',
        4051 => 'Death Knight',
        4052 => 'Dark Collector',
        4054 => 'Rune Knight',
        4055 => 'Warlock',
        4056 => 'Ranger',
        4057 => 'Arch Bishop',
        4058 => 'Mechanic',
        4059 => 'Guillotine Cross',
        4060 => 'Rune Knight+',
        4061 => 'Warlock+',
        4062 => 'Ranger+',
        4063 => 'Arch Bishop+',
        4064 => 'Mechanic+',
        4065 => 'Guillotine Cross+',
        4066 => 'Royal Guard',
        4067 => 'Sorcerer',
        4068 => 'Minstrel',
        4069 => 'Wanderer',
        4070 => 'Sura',
        4071 => 'Genetic',
        4072 => 'Shadow Chaser',
        4073 => 'Royal Guard+',
        4074 => 'Sorcerer+',
        4075 => 'Minstrel+',
        4076 => 'Wanderer+',
        4077 => 'Sura+',
        4078 => 'Genetic+',
        4079 => 'Shadow Chaser+',
        4096 => 'Baby Rune Knight',
        4097 => 'Baby Warlock',
        4098 => 'Baby Ranger',
        4099 => 'Baby Arch Bishop',
        4100 => 'Baby Mechanic',
        4101 => 'Baby Guillotine Cross',
        4102 => 'Baby Royal Guard',
        4103 => 'Baby Sorcerer',
        4104 => 'Baby Minstrel',
        4105 => 'Baby Wanderer',
        4106 => 'Baby Sura',
        4107 => 'Baby Genetic',
        4108 => 'Baby Shadow Chaser',
        4190 => 'Expanded Super Novice',
        4191 => 'Expanded Super Baby',
        4211 => 'Kagerou',
        4212 => 'Oboro',
        4215 => 'Rebellion',
        4218 => 'Summoner',
        4220 => 'Baby Summoner',
        4222 => 'Baby Ninja',
        4223 => 'Baby Kagero',
        4224 => 'Baby Oboro',
        4225 => 'Baby Taekwon',
        4226 => 'Baby Star Gladiator',
        4227 => 'Baby Soul Linker',
        4228 => 'Baby Gunslinger',
        4229 => 'Baby Rebellion',
        4239 => 'Star Emperor',
        4240 => 'Soul Reaper',
        4241 => 'Baby Star Emperor',
        4242 => 'Baby Soul Reaper',
        4252 => 'Dragon Knight',
        4253 => 'Meister',
        4254 => 'Shadow Cross',
        4255 => 'Arch Mage',
        4256 => 'Cardinal',
        4257 => 'WindHawk',
        4258 => 'Imperial Guard',
        4259 => 'Biolo',
        4260 => 'Abyss Chaser',
        4261 => 'Elemental Master',
        4262 => 'Inquisitor',
        4263 => 'Troubadour',
        4264 => 'Trouvere',
        4302 => 'Sky Emperor',
        4303 => 'Soul Ascetic',
        4304 => 'Shinkiro',
        4305 => 'Shiranui',
        4306 => 'Night Watch',
        4307 => 'Hyper Novice',
        4308 => 'Spirit Handler',
    ],

    /*
     * Values of homunculus.class.
     */
    'homunculus' => [
        6001 => 'Lif',
        6009 => 'Lif',
        6005 => 'Lif',
        6013 => 'Lif',
        6002 => 'Amistr',
        6010 => 'Amistr',
        6006 => 'Amistr',
        6014 => 'Amistr',
        6003 => 'Filir',
        6011 => 'Filir',
        6007 => 'Filir',
        6015 => 'Filir',
        6004 => 'Vanilmirth',
        6012 => 'Vanilmirth',
        6008 => 'Vanilmirth',
        6016 => 'Vanilmirth',
        6048 => 'Eira',
        6049 => 'Bayeri',
        6050 => 'Sera',
        6051 => 'Dieter',
        6052 => 'Elanor',
    ],

    /*
    |--------------------------------------------------------------------------
    | Item and monster attribute columns
    |--------------------------------------------------------------------------
    |
    | Modern rAthena stores these as one boolean column per attribute rather
    | than as a bitmask: `item_db_re` has a `location_head_top` column, a
    | `job_swordman` column, a `trade_nodrop` column and so on. The maps below
    | turn those column names into labels.
    |
    | Ported from FluxCP's config/itemtypes.php, equip_locations.php,
    | equip_jobs.php, equip_upper.php, trade_restrictions.php, itemsflags.php
    | and monstermode.php.
    |
    | The job and class lists are split because the renewal entries only exist
    | on a renewal server; reading them on a pre-renewal one asks for columns
    | that are not there.
    |
    */

    'item_types' => [
        'ammo' => 'Ammo',
        'armor' => 'Armor',
        'card' => 'Card',
        'cash' => 'Cash Shop Reward',
        'delayconsume' => 'Delay Consume',
        'etc' => 'Etc',
        'healing' => 'Healing',
        'petarmor' => 'Pet Armor',
        'petegg' => 'Pet Egg',
        'shadowgear' => 'Shadow Equipment',
        'usable' => 'Usable',
        'weapon' => 'Weapon',
    ],

    'equip_locations' => [
        'location_head_top' => 'Upper Headgear',
        'location_head_mid' => 'Middle Headgear',
        'location_head_low' => 'Lower Headgear',
        'location_armor' => 'Armor',
        'location_right_hand' => 'Main Hand',
        'location_left_hand' => 'Off Hand',
        'location_garment' => 'Garment',
        'location_shoes' => 'Footgear',
        'location_right_accessory' => 'Accessory Right',
        'location_left_accessory' => 'Accessory Left',
        'location_costume_head_top' => 'Costume Top Headgear',
        'location_costume_head_mid' => 'Costume Mid Headgear',
        'location_costume_head_low' => 'Costume Low Headgear',
        'location_costume_garment' => 'Costume Garment',
        'location_ammo' => 'Ammo',
        'location_shadow_armor' => 'Shadow Armor',
        'location_shadow_weapon' => 'Shadow Weapon',
        'location_shadow_shield' => 'Shadow Shield',
        'location_shadow_shoes' => 'Shadow Shoes',
        'location_shadow_right_accessory' => 'Shadow Accessory Right (Earring)',
        'location_shadow_left_accessory' => 'Shadow Accessory Left (Pendant)',
    ],

    'equip_jobs' => [
        'base' => [
            'job_all' => 'All jobs',
            'job_novice' => 'Novice',
            'job_supernovice' => 'Super Novice',
            'job_swordman' => 'Swordman',
            'job_mage' => 'Mage',
            'job_archer' => 'Archer',
            'job_acolyte' => 'Acolyte',
            'job_merchant' => 'Merchant',
            'job_thief' => 'Thief',
            'job_knight' => 'Knight',
            'job_priest' => 'Priest',
            'job_wizard' => 'Wizard',
            'job_blacksmith' => 'Blacksmith',
            'job_hunter' => 'Hunter',
            'job_assassin' => 'Assassin',
            'job_crusader' => 'Crusader',
            'job_monk' => 'Monk',
            'job_sage' => 'Sage',
            'job_rogue' => 'Rogue',
            'job_alchemist' => 'Alchemist',
            'job_barddancer' => 'Bard / Dancer',
            'job_taekwon' => 'Taekwon',
            'job_stargladiator' => 'Star Gladiator',
            'job_soullinker' => 'Soul Linker',
            'job_gunslinger' => 'Gunslinger',
            'job_ninja' => 'Ninja',
        ],
        'renewal' => [
            'job_kagerouoboro' => 'Kagerou / Oboro',
            'job_rebellion' => 'Rebellion',
            'job_summoner' => 'Summoner',
        ],
    ],

    'equip_classes' => [
        'base' => [
            'class_all' => 'All classes',
            'class_normal' => 'Normal',
            'class_upper' => 'Upper',
            'class_baby' => 'Baby',
        ],
        'renewal' => [
            'class_third' => 'Third',
            'class_third_upper' => 'Third Upper',
            'class_third_baby' => 'Third Baby',
        ],
    ],

    'trade_restrictions' => [
        'trade_nodrop' => "Can't be dropped",
        'trade_notrade' => "Can't be traded with another player",
        'trade_tradepartner' => "Can't be traded with a partner",
        'trade_nosell' => "Can't be sold to an NPC",
        'trade_nocart' => "Can't be put in a cart",
        'trade_nostorage' => "Can't be put in storage",
        'trade_noguildstorage' => "Can't be put in guild storage",
        'trade_nomail' => "Can't be attached to mail",
        'trade_noauction' => "Can't be auctioned",
    ],

    'item_flags' => [
        'flag_buyingstore' => 'Available to buying stores',
        'flag_deadbranch' => 'Dead branch type',
        'flag_container' => 'Is a container',
        'flag_uniqueid' => 'Unique stack',
        'flag_bindonequip' => 'Bound to the character on equipping',
        'flag_dropannounce' => 'Announced to the character on drop',
        'flag_noconsume' => 'Not consumed on use',
    ],

    'monster_modes' => [
        'mode_aggressive' => 'Aggressive',
        'mode_angry' => 'Angry',
        'mode_assist' => 'Assist',
        'mode_canattack' => 'Can attack',
        'mode_canmove' => 'Can move',
        'mode_castsensorchase' => 'Cast sensor chase',
        'mode_castsensoridle' => 'Cast sensor idle',
        'mode_changechase' => 'Change chase',
        'mode_changetargetchase' => 'Change target chase',
        'mode_changetargetmelee' => 'Change target melee',
        'mode_detector' => 'Detector',
        'mode_fixeditemdrop' => 'Fixed item drop',
        'mode_ignoremagic' => 'Ignores magic',
        'mode_ignoremelee' => 'Ignores melee',
        'mode_ignoremisc' => 'Ignores misc',
        'mode_ignoreranged' => 'Ignores ranged',
        'mode_knockbackimmune' => 'Knockback immune',
        'mode_looter' => 'Looter',
        'mode_mvp' => 'MVP',
        'mode_norandomwalk' => 'Plant',
        'mode_randomtarget' => 'Random target',
        'mode_skillimmune' => 'Skill immune',
        'mode_statusimmune' => 'Status immune',
        'mode_targetweak' => 'Targets the weak',
        'mode_teleportblock' => 'Teleport block',
    ],

];
